# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'AutoLayoutFirstLevel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoLayoutFirstLevel

  target 'AutoLayoutFirstLevelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AutoLayoutFirstLevelUITests' do
    # Pods for testing
  end

end
